# Generated by Django 4.2.6 on 2023-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('imageLink', models.CharField(max_length=200)),
                ('imageName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('attendees', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateTimeField()),
            ],
        ),
    ]
