# Generated by Django 4.2.6 on 2023-10-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myEventsApp', '0002_event_host_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='imageLink',
        ),
        migrations.RemoveField(
            model_name='event',
            name='imageName',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
